
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-service-account
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster_role_binding_spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: spark-service-account
    namespace: spark
  - kind: ServiceAccount
    name: default
    namespace: spark
