apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gcs-fuse-logs
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-gcs-fuse-logs         # Must match the PV
  storageClassName: should-not-be-empty 
  # storageClassName does not need to refer to a StorageClass object.
  # Use any non-empty value to bind the PVC to the PV.
  # volumeName must match the PersistentVolume name to bind specifically.